paths:
  /v1/deployments:
    get:
      x-fern-audiences:
        - default
  /v1/deployments/{id}:
    get:
      x-fern-audiences:
        - default
  /v1/deployments/provider-payload:
    post:
      x-fern-audiences:
        - default
  /v1/document-indexes:
    get:
      x-fern-audiences:
        - default
    post:
      x-fern-audiences:
        - default
  /v1/document-indexes/{id}:
    get:
      x-fern-audiences:
        - default
  /v1/documents:
    get:
      x-fern-audiences:
        - default
  /v1/documents/{id}:
    delete:
      x-fern-audiences:
        - default
    patch:
      x-fern-audiences:
        - default
  /v1/execute-prompt:
    post:
      x-fern-audiences:
        - predict
  /v1/execute-prompt-stream:
    post:
      x-fern-audiences:
        - predict
  /v1/execute-workflow:
    post:
      x-fern-audiences:
        - predict
  /v1/execute-workflow-stream:
    post:
      x-fern-audiences:
        - predict
  /v1/folders/{folder_id}/add-entity:
    post:
      x-fern-audiences:
        - default
  /v1/generate:
    post:
      x-fern-audiences:
        - predict
  /v1/generate-stream:
    post:
      x-fern-audiences:
        - predict
  /v1/model-versions/{id}:
    get:
      x-fern-audiences:
        - default
  /v1/registered-prompts/register:
    post:
      x-fern-audiences:
        - default
  /v1/sandboxes/{id}/scenarios:
    post:
      x-fern-audiences:
        - default
  /v1/sandboxes/{id}/scenarios/{scenario_id}:
    delete:
      x-fern-audiences:
        - default
  /v1/search:
    post:
      x-fern-audiences:
        - predict
  /v1/submit-completion-actuals:
    post:
      x-fern-audiences:
        - predict
  /v1/submit-workflow-execution-actuals:
    post:
      x-fern-audiences:
        - predict
  /v1/test-suites/{id}/test-cases:
    post:
      x-fern-audiences:
        - default
  /v1/test-suites/{id}/test-cases/{test_case_id}:
    delete:
      x-fern-audiences:
        - default
  /v1/upload-document:
    post:
      x-fern-audiences:
        - documents
  /v1/workflow-deployments:
    get:
      x-fern-audiences:
        - default
  /v1/workflow-deployments/{id}:
    get:
      x-fern-audiences:
        - default
